/* AMV service worker - generated by build.mjs, do not edit. */
const CACHE = 'amv-1azgq2u';
const SHELL = '/';

self.addEventListener('install', e => { self.skipWaiting(); });

self.addEventListener('activate', e => {
  /* Retire every cache that is not this build's. Without this the old ones sit
     there for ever and a visitor can be served an app that no longer exists. */
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  /* Never the API. A cached answer about somebody's plan, balance or messages
     is worse than no answer, and a cached POST-shaped GET is a wrong one. */
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/v1/') || url.pathname.startsWith('/auth/')) return;

  /* AMV-020: A QUERY STRING ON THIS APP IS A ONE-OFF, NOT A PAGE.

     The cache is keyed by the FULL url, so every navigation carrying a query
     string was stored under it - and on a single-file app the things that carry
     one are exactly the things that must never be kept: an OAuth return with a
     code and state, a post-checkout return naming what was bought, a share link
     with its token. Storing those puts a live credential in Cache Storage,
     where script can read it, and it outlives signing out.

     There is nothing to lose by not caching them. The shell they load is the
     same shell, already cached under '/', and the offline fallback below serves
     it - so a visitor offline on one of these URLs still gets the app. */
  if (url.search) {
    e.respondWith((async () => {
      try { return await fetch(req); }
      catch (err) {
        const shell = await caches.match(SHELL);
        if (shell) return shell;
        throw err;
      }
    })());
    return;
  }

  /* And nothing that arrived with a credential attached. A request the browser
     sent an Authorization header or a cookie with is a request whose answer is
     about one person. */
  if (req.headers.get('Authorization') || req.credentials === 'include') return;

  /* NETWORK FIRST, cache as the fallback.

     The opposite - cache first - is what most offline shells do and it is
     wrong for a single-file app: every returning visitor runs the previous
     build, so the deploy that fixes a broken checkout does not reach the
     person hitting it, and a bad cached page survives redeploying. This way
     offline still works and nobody is ever a version behind. */
  e.respondWith((async () => {
    try {
      const res = await fetch(req);
      /* What the SERVER said about storing it. A service worker that ignores
         cache directives is a cache nobody can turn off: marking a response
         no-store is how a server says "this is about one person, or it can be
         revoked", and the whole point is that it cannot be predicted from the
         URL. Honoured here so the rule is a rule rather than a list of paths
         somebody has to keep extending. */
      const cc = (res && res.headers && res.headers.get('Cache-Control')) || '';
      const storable = !/no-store|private/i.test(cc);
      if (res && res.status === 200 && res.type === 'basic' && storable) {
        const c = await caches.open(CACHE);
        c.put(req, res.clone());
      }
      return res;
    } catch (err) {
      const hit = await caches.match(req);
      if (hit) return hit;
      if (req.mode === 'navigate') {
        const shell = await caches.match(SHELL);
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
