/* AMV service worker - generated by build.mjs, do not edit. */
const CACHE = 'amv-fnc3g0';
const SHELL = '/';

self.addEventListener('install', e => { self.skipWaiting(); });

self.addEventListener('activate', e => {
  /* Retire every cache that is not this build's. Without this the old ones sit
     there for ever and a visitor can be served an app that no longer exists. */
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  /* Never the API. A cached answer about somebody's plan, balance or messages
     is worse than no answer, and a cached POST-shaped GET is a wrong one. */
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/v1/') || url.pathname.startsWith('/auth/')) return;

  /* NETWORK FIRST, cache as the fallback.

     The opposite - cache first - is what most offline shells do and it is
     wrong for a single-file app: every returning visitor runs the previous
     build, so the deploy that fixes a broken checkout does not reach the
     person hitting it, and a bad cached page survives redeploying. This way
     offline still works and nobody is ever a version behind. */
  e.respondWith((async () => {
    try {
      const res = await fetch(req);
      if (res && res.status === 200 && res.type === 'basic') {
        const c = await caches.open(CACHE);
        c.put(req, res.clone());
      }
      return res;
    } catch (err) {
      const hit = await caches.match(req);
      if (hit) return hit;
      if (req.mode === 'navigate') {
        const shell = await caches.match(SHELL);
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
